#!/usr/bin/env bash
# my script

my_script () {
    script=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $script" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 1 ]
then
  my_script "$1" "www"
  my_script "$1" "lb-01"
  my_script "$1" "web-01"
  my_script "$1" "web-02"
else
  my_script "$1" "$2"
fi
