#!/usr/bin/env bash
# my script

display_dom_su () {
    dig "$1" | grep -A1 'ANSWER SECTION:' | sed -r "s/$1./$2/g" | awk -F" " ' NR==2 { print "The subdomain " $1 " is a " $4 " record and points to " $5 }'
}

if [ "$#" -eq 2 ]
then
    display_dom_su "$2.$1" "$2"
else
    display_dom_su "www.$1" "www"
    display_dom_su "lb-01.$1" "lb-01"
    display_dom_su "web-01.$1" "web-01"
    display_dom_su "web-02.$1" "web-02"
fi
