#!/usr/bin/env bash
# install and configure ngnix

sudo apt-get update
sudo apt-get -y install nginx
touch /var/www/html/index.html
chmod 666 /var/www/html/index.html
echo "Hello World!" > /var/www/html/index.html
sudo service nginx start
