#!/usr/bin/env bash
# install and configure ngnix
sudo apt-get update
sudo apt-get -y install nginx
mkdir -p /var/www/html
echo '<html><body>Hello World!</body></html>' > /var/www/html/index.html
sudo service nginx start
