#!/usr/bin/env bash
#configure a brand new machine with nginx

apt-get update
apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.7
apt-get update
apt-get install haproxy=1.7.\* -y
echo "frontend web-front
        bind *:80
        default_backend web-backend

backend web-backend
        balance roundrobin
        server 378689-web-01 107.23.107.180:80 check
        server 378689-web-02 52.3.242.207:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy start
